// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzXE3UkmqkvbIWH0ZkGbvluhz5MfbdcTU',
    appId: '1:332933676175:web:1181bcb173637642a884fa',
    messagingSenderId: '332933676175',
    projectId: 'aspireedge-b9754',
    authDomain: 'aspireedge-b9754.firebaseapp.com',
    databaseURL: 'https://aspireedge-b9754-default-rtdb.firebaseio.com',
    storageBucket: 'aspireedge-b9754.firebasestorage.app',
    measurementId: 'G-WD21DMS7WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3hvZwhwHsF24_t7GFBg0csUjXKX9oYYY',
    appId: '1:332933676175:android:96983b3283041262a884fa',
    messagingSenderId: '332933676175',
    projectId: 'aspireedge-b9754',
    databaseURL: 'https://aspireedge-b9754-default-rtdb.firebaseio.com',
    storageBucket: 'aspireedge-b9754.firebasestorage.app',
  );

}
